# Numpy 基础

如遇到不清楚的函数或主题，可以查阅[官方文档](https://numpy.org/doc/stable/user/index.html)、阅读[教程](https://www.runoob.com/numpy/numpy-tutorial.html)或利用搜索引擎寻求帮助。

## 1. 矩阵和向量

首先导入Numpy包：

In [2]:
import numpy as np

利用Numpy可以方便地创建向量和矩阵：

In [5]:
[1.0,2.0]+[1.0,2.0]

[1.0, 2.0, 1.0, 2.0]

In [7]:
vec = np.array([1.0, 2.0, 5.0])
print(vec)
print(vec+vec)


[1. 2. 5.]
[ 2.  4. 10.]


- ***在numpy中，默认情况下这种向量的拼接是按照行排列的***

In [8]:
mat = np.array([[1.0, 2.0, 2.0], [3.0, 5.0, 4.5]]) #两重列表
print(mat)

[[1.  2.  2. ]
 [3.  5.  4.5]]


* 通过`linspace`生成均匀步进的数列

In [9]:
vec = np.linspace(start=1.0, stop=5.0, num=12) 
print(vec)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


* `reshape` 进行形状改变

In [10]:
mat = np.reshape(vec, (3, 4))
print(mat)

[[1.         1.36363636 1.72727273 2.09090909]
 [2.45454545 2.81818182 3.18181818 3.54545455]
 [3.90909091 4.27272727 4.63636364 5.        ]]


In [14]:
vec.reshape(3, 4)


[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


一些特殊的向量和矩阵有专用的创建方法。1-向量/矩阵：

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

0-向量/矩阵：

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

单位阵：

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

对角矩阵：

In [20]:
d = np.array([1, 3, 5])
np.diag(d)

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

Python中***下标是从0开始的***，请一定要记住这一点，否则会造成很多逻辑错误。

In [21]:
print(vec[0])
print(vec[2])
print(mat[1, 1])

1.0
1.7272727272727273
2.8181818181818183


负数的下标表示从尾部往前数：
* `-1`表示最后一个元素（如果是-0的话就和0没区别了）

In [22]:
print(vec[-1])
print(vec[-2])
print(mat[1, -1])

5.0
4.636363636363637
3.5454545454545454


可以用冒号选取向量中的一段范围，格式为`x[start:end]`，选出的元素包含`x[start]`，不包含`x[end]`。
- *左开右闭*

In [23]:
print(vec[1:3])

[1.36363636 1.72727273]


In [24]:
print(mat[:, :2])

[[1.         1.36363636]
 [2.45454545 2.81818182]
 [3.90909091 4.27272727]]


在编写函数时，经常需要各种测试数据，此时可以用Numpy来生成各类随机数。**在需要用到随机数之前，一定要先设置随机数种子，以使结果可重复。**

In [25]:
np.random.seed(123)

生成均匀分布随机数：

In [26]:
unif = np.random.uniform(low=0.0, high=1.0, size=5)
print(unif)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


正态分布随机数：

In [27]:
norm = np.random.normal(loc=0.0, scale=1.0, size=(2, 5))
print(norm)

[[ 0.32210607 -0.05151772 -0.20420096  1.97934843 -1.61930007]
 [-1.11396442 -0.44744072  1.66840161 -0.14337247 -0.6191909 ]]


Numpy提供了许多数学函数对向量和矩阵进行操作：

In [28]:
print(unif - 0.5)

[ 0.19646919 -0.21386067 -0.27314855  0.05131477  0.21946897]


In [29]:
print(norm * 2)

[[ 0.64421214 -0.10303544 -0.40840193  3.95869687 -3.23860013]
 [-2.22792883 -0.89488144  3.33680322 -0.28674495 -1.2383818 ]]


In [30]:
print(np.exp(norm))

[[1.38003115 0.94978682 0.81529851 7.23802539 0.19803726]
 [0.32825504 0.63926211 5.30368367 0.86643129 0.53837986]]


In [31]:
print(np.log(unif))

[-0.36173173 -1.2512764  -1.48345987 -0.59544936 -0.32924188]


也可以对向量和矩阵进行汇总：

In [33]:
np.sum(unif)

2.4802437129808985

In [34]:
np.mean(norm)

-0.02291311494411293

汇总可以按行或者按列进行，这由`axis`参数决定。0表示运算时第一个维度（行）在变化，1表示运算时第二个维度（列）在变化。
再次提醒，Python中以0表示第一个元素！

In [35]:
norm

array([[ 0.32210607, -0.05151772, -0.20420096,  1.97934843, -1.61930007],
       [-1.11396442, -0.44744072,  1.66840161, -0.14337247, -0.6191909 ]])

- 记忆：前行后列，所以0行1列

In [38]:
np.mean(norm, axis=0)  # 对第一个维度（行标在变化）求均值

array([-0.39592917, -0.24947922,  0.73210032,  0.91798798, -1.11924548])

In [39]:
np.var(norm, axis=1)  # 对第二个维度（列标在变化）求方差

array([1.33033757, 0.90853666])

Numpy 中还有一种常见的操作称为广播（[教程](https://www.runoob.com/numpy/numpy-broadcast.html)），即矩阵和向量进行逐元素运算时，向量可以自动扩展以匹配矩阵的维度。考虑如下矩阵和向量：

In [40]:
mat = np.arange(12).reshape(3, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
v1 = np.arange(3)
v1

array([0, 1, 2])

In [42]:
v2 = np.arange(4)
v2

array([0, 1, 2, 3])

将 `v1` 加到 `mat` 的每一列：

In [43]:
v1.reshape(3, 1)

array([[0],
       [1],
       [2]])

In [45]:
mat + v1.reshape(3, 1)

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

将 `v2` 加到 `mat` 的每一行：

In [44]:
mat + v2.reshape(1, 4)

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

对行操作时，也可以不用 `reshape()` 直接进行运算：

In [46]:
mat + v2

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

### 练习

(a) 生成10000个服从(0, 1)间均匀分布的随机数，赋值给变量`x`，并打印其**前10个**元素。

(b) 创建向量`y`，令其在数学上等于`y=-log(x)`，其中`log`为自然对数。打印`y`的**最后10个**元素。

(c) 查找在Python中绘制图形的方法，绘制`y`的直方图。

(d) 猜测或证明`y`服从什么分布，并简要说明理由。

## 2. 线性代数操作

矩阵转置 $A^T$：

In [47]:
np.random.seed(123)
A = np.random.normal(size=(5, 3))
A

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654],
       [-2.42667924, -0.42891263,  1.26593626],
       [-0.8667404 , -0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  , -0.44398196]])

In [48]:
A.transpose()

array([[-1.0856306 , -1.50629471, -2.42667924, -0.8667404 ,  1.49138963],
       [ 0.99734545, -0.57860025, -0.42891263, -0.67888615, -0.638902  ],
       [ 0.2829785 ,  1.65143654,  1.26593626, -0.09470897, -0.44398196]])

矩阵乘法 $B=A^TA$：

In [57]:
B = np.matmul(A.transpose(), A)
B

array([[12.31177166,  0.46519338, -6.44684349],
       [ 0.46519338,  2.3825244 , -0.86831276],
       [-6.44684349, -0.86831276,  4.61600385]])

$Bx$：

In [58]:
x = np.random.normal(size=3)
Bx = np.matmul(B, x)
Bx

array([-21.58213548,  -2.89040652,  12.82454126])

也可以调用对象自己的 `dot()` 函数：

In [50]:
B = A.transpose().dot(A)
Bx = B.dot(x)
print(B)
print()
print(Bx)

[[12.31177166  0.46519338 -6.44684349]
 [ 0.46519338  2.3825244  -0.86831276]
 [-6.44684349 -0.86831276  4.61600385]]

[-18.4193173    3.15481065  10.97897045]


**注意**：如果最终目的是计算 $A^TAx$，应先计算 $Ax$，再计算 $A^T(Ax)$。（为什么？）

矩阵求逆：

In [51]:
Binv = np.linalg.inv(B)
Binv

array([[0.3272113 , 0.11021878, 0.47772586],
       [0.11021878, 0.48774192, 0.24568345],
       [0.47772586, 0.24568345, 0.93005856]])

In [52]:
Binv.dot(B)

array([[ 1.00000000e+00, -5.55111512e-17, -4.44089210e-16],
       [ 2.22044605e-16,  1.00000000e+00,  0.00000000e+00],
       [ 8.88178420e-16, -1.11022302e-16,  1.00000000e+00]])

**注意：实际计算中通常不需要显式地求逆，而应尽可能转化成解线性方程组。**

解线性方程组 $Bx=d$，即计算 $x=B^{-1}d$：

In [53]:
d = np.random.normal(size=3)
x = np.linalg.solve(B, d)
x

array([0.72336281, 0.48018414, 1.26033807])

验证解的正确性：

In [54]:
print(d)
print(B.dot(x))

[1.0040539  0.3861864  0.73736858]
[1.0040539  0.3861864  0.73736858]


求解特征值和特征向量：

In [55]:
evals, evecs = np.linalg.eigh(B)
print(evals)
print()
print(evecs)

[ 0.77881759  2.50876381 16.02271851]

[[-0.45250424 -0.20887627 -0.86695479]
 [-0.31951962  0.94561067 -0.06105468]
 [-0.83255458 -0.24938156  0.49463291]]


- 数值计算 引入

In [63]:
x = np.random.normal(size = (5,3))
y = np.random.normal(size = (5,1))
#inv = np.linalg.inv(x.transpose().dot(x))
yhat = x.dot(np.linalg.inv(x.transpose().dot(x))).dot(x.transpose().dot(y))
print(yhat)

[[-1.32113575]
 [-0.12680952]
 [ 1.28256236]
 [-0.79913986]
 [-1.5374199 ]]
